### PR TITLE
Custom widgets created.

### PR DESCRIPTION
**Pull request by aydemiromer**
I added a custom elevated button, It is a widget where you can set your button as you want and make new widgets for your own buttons.

### CODE REVIEW

**Comment by aydemiromer** [comment]
I added. a custom alert dialog for iOS and Android devices.

**Comment by VB10** [comment]
@aydemiromer could you fix problem and please add your solutions a new section like container etc.

**Comment by aydemiromer** [comment]
I fixed the conflict files.

**Review by VB10 — APPROVED** [review]
thank uu

**Pull request merged**
