### PR TITLE
Network Dependent Widget

### PR DESCRIPTION
**Pull request by themumy10**
Network dependent widget shows child  according to network status

### CODE REVIEW

**Review by VB10 — APPROVED** [review]
thank uu

**Comment by VB10** [comment]
can you add a simple gif or image ?

**Comment by themumy10** [comment]
[https://media.giphy.com/media/GswIOmdIVG0uKbVKF6/giphy.gif](url)

**Comment by themumy10** [comment]
[https://media.giphy.com/media/GswIOmdIVG0uKbVKF6/giphy.gif](url)

**Comment by themumy10** [comment]
> can you add a simple gif or image ?

https://media.giphy.com/media/GswIOmdIVG0uKbVKF6/giphy.gif

**Comment by VB10** [comment]
@themumy10 should you add in read me file this link

**Comment by VB10** [comment]
can you fix this fconlict

**Comment by themumy10** [comment]
> can you fix this fconlict

Done ✅   😊

**Review by VB10 — APPROVED** [review]
thank uu

**Pull request merged**
